language: node_js

node_js:
  - "10"

addons:
  sonarcloud:
    organization: "kamontat-github"
    token:
      secure: $SONAR_TOKEN

install:
  - yarn install

script:
  # normal analysis           - use version with build number
  # normal analysis in master - version is version, this should be real commit
  - export version="$(scripts/sh/analytic-version "$TRAVIS_PULL_REQUEST" "$TRAVIS_BRANCH" "$TRAVIS_BUILD_NUMBER")"
  - 'echo "Confirm version: $version"'
  - sonar-scanner -Dsonar.projectVersion=$version

cache:
  directories:
    - "$HOME/.sonar/cache"
    - "$HOME/.cache/yarn"
