language: node_js

node_js:
  - "10"

addons:
  sonarcloud:
    organization: "kamontat-github"
    token:
      secure: $SONAR_TOKEN

install:
  - yarn install

script:
  - export version
    # normal analysis           - use version with build number
    # normal analysis in master - version is version, this should be real commit
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    version="$(node -p "require('./package.json').version")-${TRAVIS_BUILD_NUMBER}"
    if [ "$TRAVIS_BRANCH" = "master" ]; then
    version="$(node -p "require('./package.json').version")"
    fi
    else
    version="$(node -p "require('./package.json').version")-${TRAVIS_BUILD_NUMBER}-pr"
    fi
  - sonar-scanner -Dsonar.projectVersion=$version

cache:
  directories:
    - "$HOME/.sonar/cache"
    - "$HOME/.cache/yarn"
