language: node_js

node_js:
  - "10"

addons:
  sonarcloud:
    organization: "kamontat-github"
    token:
      secure: $SONAR_TOKEN

install:
  - yarn install

script:
  - export version="$(node -p "require('./package.json').version")"
  - sonar-scanner -Dsonar.projectVersion=$version

cache:
  directories:
    - "$HOME/.sonar/cache"
    - "$HOME/.cache/yarn"
