version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v1-deps-{{ checksum "package.json" }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/repo/node_modules
            - ~/.cache ## cache both yarn and Cypress!
      - run:
          name: Running E2E tests with multiple reporters
          command: yarn test:ci
      - store_test_results:
          path: cypress/reports
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/html-report
      - store_artifacts:
          path: cypress/screenshot
