version: 2
jobs:
  test_e2e:
    docker:
      - image: cypress/base:10
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v1-deps-{{ checksum "package.json" }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/repo/node_modules
            - ~/.cache ## cache both yarn and Cypress!
      - run:
          name: Running E2E tests with multiple reporters
          command: yarn test:ci
      - store_test_results:
          path: cypress/reports
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/html-report
      - store_artifacts:
          path: cypress/screenshot
  analytic:
    docker:
      - image: newtmitch/sonar-scanner:3
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-sonar-{{ checksum "sonar-project.properties" }}
            - v1-sonar
      - run:
          name: Run analysic to Sonar cloud
          command: sonar-scanner -Dsonar.login=$SONAR_KEY -X
      - save_cache:
          key: v1-sonar-{{ checksum "sonar-project.properties" }}
          paths:
            - /root/sonar-scanner
  release:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build documents and deploy to Github page
          command: yarn gh-pages:deploy
      - run:
          name: Dump version and release github tag (power by semantic-release)
          command: yarn release
workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test_e2e
      - analytic:
          requires:
            - test_e2e
      - release:
          requires:
            - analytic
          filters:
            branches:
              only: master
